---
name: Tag Release
description: Move major version tag to the latest release commit.

on:
  release:
    types: [published]

jobs:
  tag:
    runs-on: ubuntu-24.04

    permissions:
      contents: write # Required for tag operation.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch tag history.
          persist-credentials: false

      - name: Move major version tag
        env:
          GH_TOKEN: ${{ github.token }}
          GH_TAG: ${{ github.event.release.tag_name}}
        run: |
          SHA=$(git rev-parse HEAD)
          MAJOR=${GH_TAG%%.*} # Get the major version from the tag. e.g. v1

          # Update existing tag (e.g. v1) to point to the commit hash of the release.
          gh api repos/${{ github.repository }}/git/refs/tags/${MAJOR} \
            --method PATCH --silent --field sha="$SHA" --field force=true || \
            
          # Create a new tag if it doesn't exist.
          gh api repos/${{ github.repository }}/git/refs \
            --method POST  --silent --field ref="refs/tags/${MAJOR}" --field sha="$SHA"
